# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1404-desktop"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y ruby-full

    # Rails Getting Started
    sudo apt-get install -y sqlite3 libsqlite3-dev
    sudo apt-get install -y zlib1g-dev
    sudo apt-get install -y nodejs
    sudo gem install rails

  SHELL
end
