# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1404-desktop"

  config.vm.network "private_network", ip: "192.168.30.10"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y ruby-full

    # Rails Getting Started
    sudo apt-get install -y sqlite3 libsqlite3-dev
    sudo apt-get install -y zlib1g-dev
    sudo apt-get install -y nodejs
    sudo gem install rails

  SHELL
end
