# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1404-desktop"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    curl -sL https://storage.googleapis.com/golang/go1.5.2.linux-amd64.tar.gz | sudo tar -C /usr/local/ -xz
    sudo ln -s /usr/local/go/bin/go /usr/local/bin/go

  SHELL
end
