# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1404-desktop"

  config.vm.network "private_network", ip: "192.168.30.10"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    curl -sL https://storage.googleapis.com/golang/go1.5.2.linux-amd64.tar.gz | sudo tar -C /usr/local/ -xz
    sudo ln -s /usr/local/go/bin/go /usr/local/bin/go

  SHELL
end
